// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: streaming.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamingProcessor_ProcessMediaStream_FullMethodName = "/streaming.StreamingProcessor/ProcessMediaStream"
	StreamingProcessor_GetStats_FullMethodName           = "/streaming.StreamingProcessor/GetStats"
)

// StreamingProcessorClient is the client API for StreamingProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис потоковой обработки мультимедийных данных
type StreamingProcessorClient interface {
	// Bidirectional streaming для обработки медиа-потока
	ProcessMediaStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MediaChunk, ProcessedChunk], error)
	// Получение статистики сервера
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type streamingProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingProcessorClient(cc grpc.ClientConnInterface) StreamingProcessorClient {
	return &streamingProcessorClient{cc}
}

func (c *streamingProcessorClient) ProcessMediaStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MediaChunk, ProcessedChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingProcessor_ServiceDesc.Streams[0], StreamingProcessor_ProcessMediaStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MediaChunk, ProcessedChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingProcessor_ProcessMediaStreamClient = grpc.BidiStreamingClient[MediaChunk, ProcessedChunk]

func (c *streamingProcessorClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, StreamingProcessor_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamingProcessorServer is the server API for StreamingProcessor service.
// All implementations must embed UnimplementedStreamingProcessorServer
// for forward compatibility.
//
// Сервис потоковой обработки мультимедийных данных
type StreamingProcessorServer interface {
	// Bidirectional streaming для обработки медиа-потока
	ProcessMediaStream(grpc.BidiStreamingServer[MediaChunk, ProcessedChunk]) error
	// Получение статистики сервера
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedStreamingProcessorServer()
}

// UnimplementedStreamingProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamingProcessorServer struct{}

func (UnimplementedStreamingProcessorServer) ProcessMediaStream(grpc.BidiStreamingServer[MediaChunk, ProcessedChunk]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessMediaStream not implemented")
}
func (UnimplementedStreamingProcessorServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedStreamingProcessorServer) mustEmbedUnimplementedStreamingProcessorServer() {}
func (UnimplementedStreamingProcessorServer) testEmbeddedByValue()                            {}

// UnsafeStreamingProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingProcessorServer will
// result in compilation errors.
type UnsafeStreamingProcessorServer interface {
	mustEmbedUnimplementedStreamingProcessorServer()
}

func RegisterStreamingProcessorServer(s grpc.ServiceRegistrar, srv StreamingProcessorServer) {
	// If the following call pancis, it indicates UnimplementedStreamingProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamingProcessor_ServiceDesc, srv)
}

func _StreamingProcessor_ProcessMediaStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingProcessorServer).ProcessMediaStream(&grpc.GenericServerStream[MediaChunk, ProcessedChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingProcessor_ProcessMediaStreamServer = grpc.BidiStreamingServer[MediaChunk, ProcessedChunk]

func _StreamingProcessor_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingProcessorServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingProcessor_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingProcessorServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamingProcessor_ServiceDesc is the grpc.ServiceDesc for StreamingProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.StreamingProcessor",
	HandlerType: (*StreamingProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _StreamingProcessor_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessMediaStream",
			Handler:       _StreamingProcessor_ProcessMediaStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "streaming.proto",
}
