// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: streaming.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Типы медиа-данных
type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_VIDEO       MediaType = 1
	MediaType_MEDIA_TYPE_AUDIO       MediaType = 2
	MediaType_MEDIA_TYPE_IMAGE       MediaType = 3
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_VIDEO",
		2: "MEDIA_TYPE_AUDIO",
		3: "MEDIA_TYPE_IMAGE",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_VIDEO":       1,
		"MEDIA_TYPE_AUDIO":       2,
		"MEDIA_TYPE_IMAGE":       3,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_streaming_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_streaming_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{0}
}

// Типы фильтров
type FilterType int32

const (
	FilterType_FILTER_TYPE_UNSPECIFIED   FilterType = 0
	FilterType_FILTER_TYPE_GAUSSIAN_BLUR FilterType = 1
	FilterType_FILTER_TYPE_SHARPEN       FilterType = 2
	FilterType_FILTER_TYPE_EDGE_DETECT   FilterType = 3
	FilterType_FILTER_TYPE_GRAYSCALE     FilterType = 4
)

// Enum value maps for FilterType.
var (
	FilterType_name = map[int32]string{
		0: "FILTER_TYPE_UNSPECIFIED",
		1: "FILTER_TYPE_GAUSSIAN_BLUR",
		2: "FILTER_TYPE_SHARPEN",
		3: "FILTER_TYPE_EDGE_DETECT",
		4: "FILTER_TYPE_GRAYSCALE",
	}
	FilterType_value = map[string]int32{
		"FILTER_TYPE_UNSPECIFIED":   0,
		"FILTER_TYPE_GAUSSIAN_BLUR": 1,
		"FILTER_TYPE_SHARPEN":       2,
		"FILTER_TYPE_EDGE_DETECT":   3,
		"FILTER_TYPE_GRAYSCALE":     4,
	}
)

func (x FilterType) Enum() *FilterType {
	p := new(FilterType)
	*p = x
	return p
}

func (x FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_streaming_proto_enumTypes[1].Descriptor()
}

func (FilterType) Type() protoreflect.EnumType {
	return &file_streaming_proto_enumTypes[1]
}

func (x FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterType.Descriptor instead.
func (FilterType) EnumDescriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{1}
}

// Входящий чанк медиа-данных
type MediaChunk struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Data        []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                   // Сырые данные кадра (RGB)
	Type        MediaType              `protobuf:"varint,2,opt,name=type,proto3,enum=streaming.MediaType" json:"type,omitempty"`         // Тип медиа-данных
	Width       int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`                                // Ширина кадра (для видео/изображений)
	Height      int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`                              // Высота кадра (для видео/изображений)
	Codec       string                 `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`                                 // Кодек (raw, h264, и т.д.)
	SequenceId  int64                  `protobuf:"varint,6,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`    // Порядковый номер кадра
	TimestampNs int64                  `protobuf:"varint,7,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // Временная метка в наносекундах
	// Параметры обработки
	Params        *ProcessingParams `protobuf:"bytes,8,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaChunk) Reset() {
	*x = MediaChunk{}
	mi := &file_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaChunk) ProtoMessage() {}

func (x *MediaChunk) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaChunk.ProtoReflect.Descriptor instead.
func (*MediaChunk) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *MediaChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MediaChunk) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *MediaChunk) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaChunk) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaChunk) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *MediaChunk) GetSequenceId() int64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *MediaChunk) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *MediaChunk) GetParams() *ProcessingParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// Параметры обработки
type ProcessingParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        FilterType             `protobuf:"varint,1,opt,name=filter,proto3,enum=streaming.FilterType" json:"filter,omitempty"`  // Тип фильтра
	BlurRadius    float32                `protobuf:"fixed32,2,opt,name=blur_radius,json=blurRadius,proto3" json:"blur_radius,omitempty"` // Радиус размытия (для Gaussian blur)
	Intensity     float32                `protobuf:"fixed32,3,opt,name=intensity,proto3" json:"intensity,omitempty"`                     // Интенсивность эффекта
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingParams) Reset() {
	*x = ProcessingParams{}
	mi := &file_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingParams) ProtoMessage() {}

func (x *ProcessingParams) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingParams.ProtoReflect.Descriptor instead.
func (*ProcessingParams) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessingParams) GetFilter() FilterType {
	if x != nil {
		return x.Filter
	}
	return FilterType_FILTER_TYPE_UNSPECIFIED
}

func (x *ProcessingParams) GetBlurRadius() float32 {
	if x != nil {
		return x.BlurRadius
	}
	return 0
}

func (x *ProcessingParams) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

// Обработанный чанк
type ProcessedChunk struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Data             []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                                    // Обработанные данные
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                                             // Успешность обработки
	ProcessingTimeNs int64                  `protobuf:"varint,3,opt,name=processing_time_ns,json=processingTimeNs,proto3" json:"processing_time_ns,omitempty"` // Время обработки в наносекундах
	SequenceId       int64                  `protobuf:"varint,4,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`                     // Порядковый номер (для соответствия)
	ErrorMessage     string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                // Сообщение об ошибке (если есть)
	// Метрики памяти
	MemoryMetrics *MemoryMetrics `protobuf:"bytes,6,opt,name=memory_metrics,json=memoryMetrics,proto3" json:"memory_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedChunk) Reset() {
	*x = ProcessedChunk{}
	mi := &file_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedChunk) ProtoMessage() {}

func (x *ProcessedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedChunk.ProtoReflect.Descriptor instead.
func (*ProcessedChunk) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessedChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProcessedChunk) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessedChunk) GetProcessingTimeNs() int64 {
	if x != nil {
		return x.ProcessingTimeNs
	}
	return 0
}

func (x *ProcessedChunk) GetSequenceId() int64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *ProcessedChunk) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProcessedChunk) GetMemoryMetrics() *MemoryMetrics {
	if x != nil {
		return x.MemoryMetrics
	}
	return nil
}

// Метрики использования памяти
type MemoryMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ArenaAllocatedBytes int64                  `protobuf:"varint,1,opt,name=arena_allocated_bytes,json=arenaAllocatedBytes,proto3" json:"arena_allocated_bytes,omitempty"` // Выделено из Arena
	ArenaUsedBytes      int64                  `protobuf:"varint,2,opt,name=arena_used_bytes,json=arenaUsedBytes,proto3" json:"arena_used_bytes,omitempty"`                // Используется из Arena
	TotalAllocations    int64                  `protobuf:"varint,3,opt,name=total_allocations,json=totalAllocations,proto3" json:"total_allocations,omitempty"`            // Всего аллокаций
	HeapUsedBytes       int64                  `protobuf:"varint,4,opt,name=heap_used_bytes,json=heapUsedBytes,proto3" json:"heap_used_bytes,omitempty"`                   // Используется heap памяти
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryMetrics) GetArenaAllocatedBytes() int64 {
	if x != nil {
		return x.ArenaAllocatedBytes
	}
	return 0
}

func (x *MemoryMetrics) GetArenaUsedBytes() int64 {
	if x != nil {
		return x.ArenaUsedBytes
	}
	return 0
}

func (x *MemoryMetrics) GetTotalAllocations() int64 {
	if x != nil {
		return x.TotalAllocations
	}
	return 0
}

func (x *MemoryMetrics) GetHeapUsedBytes() int64 {
	if x != nil {
		return x.HeapUsedBytes
	}
	return 0
}

// Запрос статистики
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{4}
}

// Ответ со статистикой
type StatsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalFramesProcessed  int64                  `protobuf:"varint,1,opt,name=total_frames_processed,json=totalFramesProcessed,proto3" json:"total_frames_processed,omitempty"`
	TotalProcessingTimeNs int64                  `protobuf:"varint,2,opt,name=total_processing_time_ns,json=totalProcessingTimeNs,proto3" json:"total_processing_time_ns,omitempty"`
	AvgProcessingTimeMs   float64                `protobuf:"fixed64,3,opt,name=avg_processing_time_ms,json=avgProcessingTimeMs,proto3" json:"avg_processing_time_ms,omitempty"`
	CurrentArenaSizeBytes int64                  `protobuf:"varint,4,opt,name=current_arena_size_bytes,json=currentArenaSizeBytes,proto3" json:"current_arena_size_bytes,omitempty"`
	PeakArenaSizeBytes    int64                  `protobuf:"varint,5,opt,name=peak_arena_size_bytes,json=peakArenaSizeBytes,proto3" json:"peak_arena_size_bytes,omitempty"`
	TotalArenaAllocations int64                  `protobuf:"varint,6,opt,name=total_arena_allocations,json=totalArenaAllocations,proto3" json:"total_arena_allocations,omitempty"`
	TotalArenaResets      int64                  `protobuf:"varint,7,opt,name=total_arena_resets,json=totalArenaResets,proto3" json:"total_arena_resets,omitempty"`
	FramesPerSecond       float64                `protobuf:"fixed64,8,opt,name=frames_per_second,json=framesPerSecond,proto3" json:"frames_per_second,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *StatsResponse) GetTotalFramesProcessed() int64 {
	if x != nil {
		return x.TotalFramesProcessed
	}
	return 0
}

func (x *StatsResponse) GetTotalProcessingTimeNs() int64 {
	if x != nil {
		return x.TotalProcessingTimeNs
	}
	return 0
}

func (x *StatsResponse) GetAvgProcessingTimeMs() float64 {
	if x != nil {
		return x.AvgProcessingTimeMs
	}
	return 0
}

func (x *StatsResponse) GetCurrentArenaSizeBytes() int64 {
	if x != nil {
		return x.CurrentArenaSizeBytes
	}
	return 0
}

func (x *StatsResponse) GetPeakArenaSizeBytes() int64 {
	if x != nil {
		return x.PeakArenaSizeBytes
	}
	return 0
}

func (x *StatsResponse) GetTotalArenaAllocations() int64 {
	if x != nil {
		return x.TotalArenaAllocations
	}
	return 0
}

func (x *StatsResponse) GetTotalArenaResets() int64 {
	if x != nil {
		return x.TotalArenaResets
	}
	return 0
}

func (x *StatsResponse) GetFramesPerSecond() float64 {
	if x != nil {
		return x.FramesPerSecond
	}
	return 0
}

var File_streaming_proto protoreflect.FileDescriptor

const file_streaming_proto_rawDesc = "" +
	"\n" +
	"\x0fstreaming.proto\x12\tstreaming\"\x87\x02\n" +
	"\n" +
	"MediaChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.streaming.MediaTypeR\x04type\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\x12\x1f\n" +
	"\vsequence_id\x18\x06 \x01(\x03R\n" +
	"sequenceId\x12!\n" +
	"\ftimestamp_ns\x18\a \x01(\x03R\vtimestampNs\x123\n" +
	"\x06params\x18\b \x01(\v2\x1b.streaming.ProcessingParamsR\x06params\"\x80\x01\n" +
	"\x10ProcessingParams\x12-\n" +
	"\x06filter\x18\x01 \x01(\x0e2\x15.streaming.FilterTypeR\x06filter\x12\x1f\n" +
	"\vblur_radius\x18\x02 \x01(\x02R\n" +
	"blurRadius\x12\x1c\n" +
	"\tintensity\x18\x03 \x01(\x02R\tintensity\"\xf3\x01\n" +
	"\x0eProcessedChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12,\n" +
	"\x12processing_time_ns\x18\x03 \x01(\x03R\x10processingTimeNs\x12\x1f\n" +
	"\vsequence_id\x18\x04 \x01(\x03R\n" +
	"sequenceId\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12?\n" +
	"\x0ememory_metrics\x18\x06 \x01(\v2\x18.streaming.MemoryMetricsR\rmemoryMetrics\"\xc2\x01\n" +
	"\rMemoryMetrics\x122\n" +
	"\x15arena_allocated_bytes\x18\x01 \x01(\x03R\x13arenaAllocatedBytes\x12(\n" +
	"\x10arena_used_bytes\x18\x02 \x01(\x03R\x0earenaUsedBytes\x12+\n" +
	"\x11total_allocations\x18\x03 \x01(\x03R\x10totalAllocations\x12&\n" +
	"\x0fheap_used_bytes\x18\x04 \x01(\x03R\rheapUsedBytes\"\x0e\n" +
	"\fStatsRequest\"\xb1\x03\n" +
	"\rStatsResponse\x124\n" +
	"\x16total_frames_processed\x18\x01 \x01(\x03R\x14totalFramesProcessed\x127\n" +
	"\x18total_processing_time_ns\x18\x02 \x01(\x03R\x15totalProcessingTimeNs\x123\n" +
	"\x16avg_processing_time_ms\x18\x03 \x01(\x01R\x13avgProcessingTimeMs\x127\n" +
	"\x18current_arena_size_bytes\x18\x04 \x01(\x03R\x15currentArenaSizeBytes\x121\n" +
	"\x15peak_arena_size_bytes\x18\x05 \x01(\x03R\x12peakArenaSizeBytes\x126\n" +
	"\x17total_arena_allocations\x18\x06 \x01(\x03R\x15totalArenaAllocations\x12,\n" +
	"\x12total_arena_resets\x18\a \x01(\x03R\x10totalArenaResets\x12*\n" +
	"\x11frames_per_second\x18\b \x01(\x01R\x0fframesPerSecond*i\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_AUDIO\x10\x02\x12\x14\n" +
	"\x10MEDIA_TYPE_IMAGE\x10\x03*\x99\x01\n" +
	"\n" +
	"FilterType\x12\x1b\n" +
	"\x17FILTER_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FILTER_TYPE_GAUSSIAN_BLUR\x10\x01\x12\x17\n" +
	"\x13FILTER_TYPE_SHARPEN\x10\x02\x12\x1b\n" +
	"\x17FILTER_TYPE_EDGE_DETECT\x10\x03\x12\x19\n" +
	"\x15FILTER_TYPE_GRAYSCALE\x10\x042\x9f\x01\n" +
	"\x12StreamingProcessor\x12J\n" +
	"\x12ProcessMediaStream\x12\x15.streaming.MediaChunk\x1a\x19.streaming.ProcessedChunk(\x010\x01\x12=\n" +
	"\bGetStats\x12\x17.streaming.StatsRequest\x1a\x18.streaming.StatsResponseB#Z!github.com/streaming-system/protob\x06proto3"

var (
	file_streaming_proto_rawDescOnce sync.Once
	file_streaming_proto_rawDescData []byte
)

func file_streaming_proto_rawDescGZIP() []byte {
	file_streaming_proto_rawDescOnce.Do(func() {
		file_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)))
	})
	return file_streaming_proto_rawDescData
}

var file_streaming_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_streaming_proto_goTypes = []any{
	(MediaType)(0),           // 0: streaming.MediaType
	(FilterType)(0),          // 1: streaming.FilterType
	(*MediaChunk)(nil),       // 2: streaming.MediaChunk
	(*ProcessingParams)(nil), // 3: streaming.ProcessingParams
	(*ProcessedChunk)(nil),   // 4: streaming.ProcessedChunk
	(*MemoryMetrics)(nil),    // 5: streaming.MemoryMetrics
	(*StatsRequest)(nil),     // 6: streaming.StatsRequest
	(*StatsResponse)(nil),    // 7: streaming.StatsResponse
}
var file_streaming_proto_depIdxs = []int32{
	0, // 0: streaming.MediaChunk.type:type_name -> streaming.MediaType
	3, // 1: streaming.MediaChunk.params:type_name -> streaming.ProcessingParams
	1, // 2: streaming.ProcessingParams.filter:type_name -> streaming.FilterType
	5, // 3: streaming.ProcessedChunk.memory_metrics:type_name -> streaming.MemoryMetrics
	2, // 4: streaming.StreamingProcessor.ProcessMediaStream:input_type -> streaming.MediaChunk
	6, // 5: streaming.StreamingProcessor.GetStats:input_type -> streaming.StatsRequest
	4, // 6: streaming.StreamingProcessor.ProcessMediaStream:output_type -> streaming.ProcessedChunk
	7, // 7: streaming.StreamingProcessor.GetStats:output_type -> streaming.StatsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_streaming_proto_init() }
func file_streaming_proto_init() {
	if File_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streaming_proto_goTypes,
		DependencyIndexes: file_streaming_proto_depIdxs,
		EnumInfos:         file_streaming_proto_enumTypes,
		MessageInfos:      file_streaming_proto_msgTypes,
	}.Build()
	File_streaming_proto = out.File
	file_streaming_proto_goTypes = nil
	file_streaming_proto_depIdxs = nil
}
